import { RequiredDataFromCollectionSlug } from 'payload'

export const findOrderPageData = (): RequiredDataFromCollectionSlug<'pages'> => {
  return {
    slug: "find-order",
    _status: "published",
    title: "Find Your Order",
    meta: {
      title: "Find Your Order | Track Ghorer Bazar Delivery",
      description: "Track your Ghorer Bazar order status, view tracking IDs, and review delivery progress in real time.",
    },
    layout: [
      {
        blockName: "Find Your Order content",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 1,
                        mode: "normal",
                        style: "",
                        text: "DRAFT — replace with final legal copy.",
                        version: 1,
                      },
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: " This page is structured for AI/search citation; legal text needs review by counsel before launch.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Find Your Order",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h1",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "You can track every Ghorer Bazar order from purchase to doorstep. This page explains the easiest ways to look up your order status, find your tracking ID, and resolve common tracking issues.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Track from your account",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Sign in and open “My Orders.” Each order shows real-time status: Confirmed → Packed → Dispatched → Out for Delivery → Delivered, plus the courier tracking link.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Track as a guest",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "No account? Visit the Find My Order page in the footer, enter your order number and the phone or email used at checkout, and we will pull your status.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "SMS and email updates",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "We send an SMS and email at each major status change. If you have stopped receiving updates, check your contact details in your account settings.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Stuck in transit?",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "If your tracking has not updated for 48 hours after dispatch, please contact support@ghorerbazar.com with your order number. We escalate with the courier directly.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Wrong address?",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "If you noticed an address mistake, contact us within two hours of placing the order. After dispatch we cannot change the destination but can arrange a refused-delivery return.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
      {
        blockName: "FAQ",
        blockType: "faq",
        heading: "Order tracking questions",
        subheading: "Quick answers if your delivery seems delayed.",
        items: [
          {
            question: "My status says “Delivered” but I did not receive it—what now?",
            answer: "Email support@ghorerbazar.com within 24 hours of the delivered status. We will check the proof of delivery photo and signature with the courier and resolve within 48 hours.",
          },
          {
            question: "Can someone else receive the parcel for me?",
            answer: "Yes. Anyone at the delivery address can accept the parcel by sharing the OTP we sent you. Please share the OTP only with people you trust.",
          },
          {
            question: "Why is my order taking longer than the estimate?",
            answer: "Weather, public holidays, and rural-route bottlenecks occasionally extend timelines by 1–2 days. If a delay exceeds the estimate by more than two days, contact support for a courier escalation.",
          },
        ],
      },
      {
        blockName: "Footer note",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 2,
                        mode: "normal",
                        style: "",
                        text: "Last updated: 23 June 2026",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Questions? Contact us at support@ghorerbazar.com",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
    ],
  }
}
