import { RequiredDataFromCollectionSlug } from 'payload'

export const preOrderPageData = (): RequiredDataFromCollectionSlug<'pages'> => {
  return {
    slug: "pre-order",
    _status: "published",
    title: "Pre-Order Policy",
    meta: {
      title: "Pre-Order Policy | Ghorer Bazar",
      description: "How pre-orders work on Ghorer Bazar—payment, expected dispatch dates, and cancellation rights.",
    },
    layout: [
      {
        blockName: "Pre-Order Policy content",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 1,
                        mode: "normal",
                        style: "",
                        text: "DRAFT — replace with final legal copy.",
                        version: 1,
                      },
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: " This page is structured for AI/search citation; legal text needs review by counsel before launch.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Pre-Order Policy",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h1",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Some Ghorer Bazar products are offered as pre-orders, allowing you to reserve stock before it arrives in our warehouse. This page explains how pre-orders are processed, when you are charged, and how to cancel if plans change.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "What is a pre-order?",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "A pre-order lets you reserve an item that is on its way to our warehouse. Pre-order products are clearly marked on the product page along with an estimated dispatch date.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Payment",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Pre-orders are charged in full at checkout to secure your reservation. If you prefer, you can split payment with a 50% deposit by selecting the partial-payment option where available.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Estimated dispatch",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Dispatch dates shown on the product page are estimates based on supplier timelines. If a delay is expected we email you within 48 hours of learning about it.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Cancelling a pre-order",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "You can cancel a pre-order any time before dispatch and receive a full refund. After dispatch the order follows our standard Return & Refund Policy.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Mixed-cart orders",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "If you order pre-order items together with in-stock items, the whole order ships only when the pre-order arrives. Use a separate order if you need the in-stock items sooner.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
      {
        blockName: "FAQ",
        blockType: "faq",
        heading: "Pre-order questions",
        subheading: "Common questions about reserving upcoming stock.",
        items: [
          {
            question: "What happens if a pre-order is significantly delayed?",
            answer: "If dispatch is delayed by more than 30 days beyond the estimate, we will email you and offer either a full refund or a discount on the final price.",
          },
          {
            question: "Can I change the variant of a pre-order item?",
            answer: "Yes, you can change size, flavour, or colour before dispatch. Contact support@ghorerbazar.com with your order number and the variant you want.",
          },
          {
            question: "Will the price change after I pre-order?",
            answer: "No. The price you pay at pre-order is locked in even if the final retail price changes.",
          },
        ],
      },
      {
        blockName: "Footer note",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 2,
                        mode: "normal",
                        style: "",
                        text: "Last updated: 23 June 2026",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Questions? Contact us at support@ghorerbazar.com",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
    ],
  }
}
