import { RequiredDataFromCollectionSlug } from 'payload'

export const shippingPolicyPageData = (): RequiredDataFromCollectionSlug<'pages'> => {
  return {
    slug: "shipping-policy",
    _status: "published",
    title: "Shipping Policy",
    meta: {
      title: "Shipping Policy | Ghorer Bazar Delivery",
      description: "Delivery zones, lead times, and shipping charges for Ghorer Bazar orders within Bangladesh.",
    },
    layout: [
      {
        blockName: "Shipping Policy content",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 1,
                        mode: "normal",
                        style: "",
                        text: "DRAFT — replace with final legal copy.",
                        version: 1,
                      },
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: " This page is structured for AI/search citation; legal text needs review by counsel before launch.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Shipping Policy",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h1",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Ghorer Bazar ships nationwide across Bangladesh through trusted courier partners. Most orders are dispatched within 24 hours and delivered to your door within 1–5 business days depending on your location. Below you will find the details on coverage, fees, and tracking.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Delivery zones",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "We deliver to all 64 districts of Bangladesh. Dhaka inner-city orders are typically delivered within 24–48 hours, while orders outside Dhaka arrive within 2–5 business days.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Shipping charges",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Inside Dhaka delivery is 60 BDT; outside Dhaka delivery is 120 BDT. We offer free shipping on orders above 2,000 BDT within Bangladesh, subject to active promotions at checkout.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Order processing",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Orders confirmed before 4 PM are dispatched the same day; orders received after 4 PM ship the next business day. Holidays and Friday closures may extend processing by one day.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Tracking your order",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Once dispatched, you will receive an SMS with your courier tracking number. You can also sign in to your account or visit the Find My Order page for live status updates.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Failed deliveries",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "If the courier cannot reach you after two attempts, the parcel is returned to our warehouse. We will contact you to arrange a re-delivery; an additional shipping fee may apply.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
      {
        blockName: "FAQ",
        blockType: "faq",
        heading: "Shipping questions",
        subheading: "Quick answers about delivery times and charges.",
        items: [
          {
            question: "Do you offer same-day delivery in Dhaka?",
            answer: "For select Dhaka neighbourhoods we offer same-day delivery on orders placed before 12 PM. Available zones are listed at checkout.",
          },
          {
            question: "Can I change my delivery address after ordering?",
            answer: "Yes, if your order has not yet been dispatched. Contact support@ghorerbazar.com with your order number within two hours of placing the order.",
          },
          {
            question: "Do you ship outside Bangladesh?",
            answer: "Not at the moment. International shipping is on our roadmap; subscribe to the newsletter to be notified when it launches.",
          },
        ],
      },
      {
        blockName: "Footer note",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 2,
                        mode: "normal",
                        style: "",
                        text: "Last updated: 23 June 2026",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Questions? Contact us at support@ghorerbazar.com",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
    ],
  }
}
