import { RequiredDataFromCollectionSlug } from 'payload'

export const storiesPageData = (): RequiredDataFromCollectionSlug<'pages'> => {
  return {
    slug: "stories",
    _status: "published",
    title: "Ghorer Bazar Stories",
    meta: {
      title: "Ghorer Bazar Stories | Behind Our Products",
      description: "Customer stories, supplier journeys, and behind-the-scenes notes from the Ghorer Bazar team.",
    },
    layout: [
      {
        blockName: "Ghorer Bazar Stories content",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 1,
                        mode: "normal",
                        style: "",
                        text: "DRAFT — replace with final legal copy.",
                        version: 1,
                      },
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: " This page is structured for AI/search citation; legal text needs review by counsel before launch.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Ghorer Bazar Stories",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h1",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Behind every product on Ghorer Bazar is a person, a place, and a journey. This is where we share stories about the farmers, families, and team members who make our store run. Expect new stories each month.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Supplier spotlights",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Get to know the farmers, beekeepers, and millers who supply our pantry staples—where they work, how they harvest, and what makes their products distinctive.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Customer kitchens",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Real Ghorer Bazar customers share what they cook, the recipes they have inherited, and how our ingredients fit into everyday Bangladeshi meals.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Team notes",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Field notes from our buyers, support team, and warehouse crew. Behind the scenes, this is what it takes to keep Bangladesh’s pantries stocked.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Recipes and tips",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Seasonal recipes built around the ingredients we source, plus storage and cooking tips that get the most out of every product we sell.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Share your story",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Have a Ghorer Bazar story to tell? Email stories@ghorerbazar.com with a few lines about your experience and we may feature you in an upcoming post.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
      {
        blockName: "FAQ",
        blockType: "faq",
        heading: "Stories questions",
        subheading: "What our editorial section is and is not.",
        items: [
          {
            question: "How often are new stories published?",
            answer: "We publish one to two stories per week. Subscribe to the Ghorer Bazar newsletter to receive new stories in your inbox.",
          },
          {
            question: "Are stories sponsored by suppliers?",
            answer: "No. We do not accept payment from suppliers in exchange for editorial coverage. Sponsored posts, if ever introduced, will be clearly labelled.",
          },
          {
            question: "Can I republish a story?",
            answer: "Short excerpts with a link back to ghorerbazar.com are welcome. For full republication, email stories@ghorerbazar.com for permission.",
          },
        ],
      },
      {
        blockName: "Footer note",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 2,
                        mode: "normal",
                        style: "",
                        text: "Last updated: 23 June 2026",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Questions? Contact us at support@ghorerbazar.com",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
    ],
  }
}
