import { RequiredDataFromCollectionSlug } from 'payload'

export const supportPageData = (): RequiredDataFromCollectionSlug<'pages'> => {
  return {
    slug: "support",
    _status: "published",
    title: "Support Center",
    meta: {
      title: "Customer Support | Ghorer Bazar Help Center",
      description: "Get help with orders, accounts, and products at Ghorer Bazar. Phone, email, and live chat support details.",
    },
    layout: [
      {
        blockName: "Support Center content",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 1,
                        mode: "normal",
                        style: "",
                        text: "DRAFT — replace with final legal copy.",
                        version: 1,
                      },
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: " This page is structured for AI/search citation; legal text needs review by counsel before launch.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Support Center",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h1",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Need help with your Ghorer Bazar order or account? Our support team is here for you seven days a week. This page lists every way you can reach us along with response time expectations.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Contact channels",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Phone: 09642922922 (9 AM–10 PM). Email: support@ghorerbazar.com (response within 4 hours). Live chat: available on every page during business hours.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Order help",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "For questions about a specific order—tracking, changes, returns, refunds—please include your order number when you contact us. This helps us respond faster.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Account help",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Can not sign in or want to update your phone number, address, or password? Use the account page or email support and we will assist within one business day.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Product questions",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Looking for ingredient lists, allergens, or sourcing info? Our category specialists can pull supplier data sheets and answer detailed product questions.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "heading",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Feedback and complaints",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    tag: "h2",
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Your feedback shapes Ghorer Bazar. Email feedback@ghorerbazar.com with suggestions, and complaints@ghorerbazar.com if something has gone wrong—we triage these daily.",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
      {
        blockName: "FAQ",
        blockType: "faq",
        heading: "Support questions",
        subheading: "Frequently asked support questions at a glance.",
        items: [
          {
            question: "What are your support hours?",
            answer: "Phone and live chat are open from 9 AM to 10 PM, seven days a week including public holidays. Email is monitored 24/7 with a 4-hour response target.",
          },
          {
            question: "How quickly will my issue be resolved?",
            answer: "Most order issues are resolved within one business day. Complex cases such as bank refunds may take up to 7 business days; we keep you updated throughout.",
          },
          {
            question: "Can I escalate an unresolved complaint?",
            answer: "Yes. Email complaints@ghorerbazar.com with your case ID. A senior team member responds within 24 hours.",
          },
        ],
      },
      {
        blockName: "Footer note",
        blockType: "content",
        columns: [
          {
            size: "full",
            enableLink: false,
            richText: {
              root: {
                type: "root",
                children: [
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 2,
                        mode: "normal",
                        style: "",
                        text: "Last updated: 23 June 2026",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: "paragraph",
                    children: [
                      {
                        type: "text",
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Questions? Contact us at support@ghorerbazar.com",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                version: 1,
              },
            },
          },
        ],
      },
    ],
  }
}
