/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    'blog-comments': BlogComment;
    categories: Category;
    subcategories: Subcategory;
    brands: Brand;
    media: Media;
    wishlists: Wishlist;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    'promo-codes': PromoCode;
    'product-reviews': ProductReview;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    shipments: Shipment;
    'notification-preferences': NotificationPreference;
    'push-subscriptions': PushSubscription;
    'product-alerts': ProductAlert;
    'user-notifications': UserNotification;
    'notification-broadcasts': NotificationBroadcast;
    'sales-dashboard': SalesDashboard;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'subcategories';
    };
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
      wishlist: 'wishlists';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'blog-comments': BlogCommentsSelect<false> | BlogCommentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    'product-reviews': ProductReviewsSelect<false> | ProductReviewsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    shipments: ShipmentsSelect<false> | ShipmentsSelect<true>;
    'notification-preferences': NotificationPreferencesSelect<false> | NotificationPreferencesSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'product-alerts': ProductAlertsSelect<false> | ProductAlertsSelect<true>;
    'user-notifications': UserNotificationsSelect<false> | UserNotificationsSelect<true>;
    'notification-broadcasts': NotificationBroadcastsSelect<false> | NotificationBroadcastsSelect<true>;
    'sales-dashboard': SalesDashboardSelect<false> | SalesDashboardSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | BrandsCarouselBlock
    | FeaturedCategoriesBlock
    | ThreeItemGridBlock
    | TopSellingProductsBlock
    | ProductShowcaseBlock
    | ExclusiveComboDealsBlock
    | TwoImagePromoBlock
    | SingleImageBannerBlock
    | PromoCarouselSplitBlock
    | TestimonialsBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  image?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  subcategories?: {
    docs?: (number | Subcategory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  title: string;
  /**
   * Parent category — e.g. "Honey".
   */
  parent: number | Category;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        variantOption?: (number | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInBDTEnabled?: boolean | null;
  priceInBDT?: number | null;
  /**
   * Optional discount percentage shown as "Save X%" on product cards.
   */
  discountPercentage?: number | null;
  /**
   * Optional badge text shown on product cards, for example "Best Selling".
   */
  productBadge?: string | null;
  /**
   * Optional rows shown on the product comparison page (e.g. Material, Weight).
   */
  technicalSpecs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Rolling average of approved star ratings (1–5). Maintained automatically.
   */
  reviewAverageRating?: number | null;
  /**
   * Count of approved reviews. Maintained automatically.
   */
  reviewCount?: number | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Pick at least one category before assigning subcategories below.
   */
  categories?: (number | Category)[] | null;
  /**
   * Filter options reflect the categories chosen above (select categories first).
   */
  subcategories?: (number | Subcategory)[] | null;
  brand?: (number | null) | Brand;
  /**
   * Delivery pricing profile (Dhaka / outside Dhaka charges and cumulative rules). Used for checkout when this product is in the cart.
   */
  shipment?: (number | null) | Shipment;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInBDTEnabled?: boolean | null;
  priceInBDT?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Delivery charge profiles by zone (Dhaka vs outside Dhaka, point vs home). Use cumulative rules to add extra freight by product count.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments".
 */
export interface Shipment {
  id: number;
  shippingName: string;
  /**
   * Pickup / point delivery in BDT.
   */
  dhakaPointDeliveryCharge?: number | null;
  /**
   * Door-to-door in Dhaka metro (BDT).
   */
  dhakaHomeDeliveryCharge?: number | null;
  outsideDhakaPointDeliveryCharge?: number | null;
  outsideDhakaHomeDeliveryCharge?: number | null;
  freeDelivery?: boolean | null;
  /**
   * How many products complete one increment (e.g. 2 → charge increases every 2 items).
   */
  cumulativeCount?: number | null;
  /**
   * BDT added each time the cumulative count is reached.
   */
  cumulativeCharge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandsCarouselBlock".
 */
export interface BrandsCarouselBlock {
  heading?: string | null;
  /**
   * Order is preserved in the carousel. Each brand should have a slug and logo for best results.
   */
  brands: (number | Brand)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCategoriesBlock".
 */
export interface FeaturedCategoriesBlock {
  heading?: string | null;
  /**
   * Order is preserved in the carousel. Each category needs an image for the best appearance.
   */
  categories: (number | Category)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCategories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TopSellingProductsBlock".
 */
export interface TopSellingProductsBlock {
  heading?: string | null;
  /**
   * Pick products in display order (e.g. up to four in a two-column grid). Use Product Badge in each product’s admin for the ribbon text.
   */
  products: (number | Product)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'topSellingProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseBlock".
 */
export interface ProductShowcaseBlock {
  heading: string;
  /**
   * Link for “View all items” (e.g. /products or a full URL). Leave empty to hide the link.
   */
  viewAllUrl?: string | null;
  /**
   * Drag rows to set carousel order. Badges use each product’s Product Badge and discount fields.
   */
  products: (number | Product)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'productShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExclusiveComboDealsBlock".
 */
export interface ExclusiveComboDealsBlock {
  heading: string;
  /**
   * Link for “View All Combos” (e.g. /products?tag=combos). Leave empty to hide the button.
   */
  viewAllUrl?: string | null;
  /**
   * Pick combo products in carousel order. Discount percentage drives the green “Save” badge.
   */
  products: (number | Product)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'exclusiveComboDeals';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoImagePromoBlock".
 */
export interface TwoImagePromoBlock {
  /**
   * Left promotional tile (e.g. desktop: left half of the row).
   */
  leftImage: number | Media;
  /**
   * Right promotional tile.
   */
  rightImage: number | Media;
  leftLink: string;
  rightLink: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoImagePromo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SingleImageBannerBlock".
 */
export interface SingleImageBannerBlock {
  /**
   * Wide banner image (recommended ~1600×400px or similar). Text baked into the image is fine.
   */
  image: number | Media;
  /**
   * Optional destination when the banner is clicked (e.g. /products or a category URL).
   */
  link?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'singleImageBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoCarouselSplitBlock".
 */
export interface PromoCarouselSplitBlock {
  /**
   * Left column: rotating slides. Each slide is clickable.
   */
  slides?:
    | {
        image: number | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Static banner in the narrower right column.
   */
  rightImage: number | Media;
  rightLink: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoCarouselSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  items: {
    quote: string;
    photo: number | Media;
    name: string;
    /**
     * e.g. Entrepreneur, Student
     */
    role?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  publishedOn?: string | null;
  author?: (number | null) | User;
  /**
   * Suggested posts displayed in the sidebar while editing this post.
   */
  relatedPosts?: (number | Post)[] | null;
  /**
   * Short summary shown on the blog index.
   */
  excerpt?: string | null;
  /**
   * Paste a watch, shorts, embed, or youtu.be link. When set, the blog index shows that video thumbnail instead of Featured image.
   */
  featuredYoutubeUrl?: string | null;
  /**
   * Displayed on listing and article. Use Featured YouTube URL to show a video thumbnail on the blog index instead of this image.
   */
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  phone?: string | null;
  address?: string | null;
  roles?: ('admin' | 'customer' | 'officeStaff')[] | null;
  /**
   * Page-level and action-level permissions for office staff. Only admins can edit.
   */
  staffPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Synced from staffPermissions on save (relational storage).
   */
  staffGrants?:
    | {
        page:
          | 'pages'
          | 'posts'
          | 'blog-comments'
          | 'categories'
          | 'subcategories'
          | 'brands'
          | 'media'
          | 'forms'
          | 'form-submissions'
          | 'products'
          | 'orders'
          | 'carts'
          | 'transactions'
          | 'promo-codes'
          | 'product-reviews'
          | 'shipments'
          | 'wishlists'
          | 'users'
          | 'notification-preferences'
          | 'notification-broadcasts'
          | 'user-notifications'
          | 'push-subscriptions'
          | 'product-alerts'
          | 'sales-dashboard'
          | 'header'
          | 'footer';
        actions: ('view' | 'create' | 'edit' | 'delete' | 'approve')[];
        id?: string | null;
      }[]
    | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  wishlist?: {
    docs?: (number | Wishlist)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress: {
    district: string;
    fullAddress: string;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'BDT' | null;
  checkoutCart?: (number | null) | Cart;
  appliedPromoCode?: string | null;
  promoCode?: (number | null) | PromoCode;
  promoDiscountAmount?: number | null;
  subtotalBeforeDiscount?: number | null;
  /**
   * Shared when one checkout creates multiple orders (different shipment profiles).
   */
  checkoutBatchId?: string | null;
  /**
   * Shipment group, delivery prefs, and charge lines (base + cumulative) for this order.
   */
  checkoutShipmentSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shipmentName?: string | null;
  shipmentCharge?: string | null;
  fulfillment?: {
    trackingNumber?: string | null;
    carrier?: ('manual' | 'steadfast' | 'pathao' | 'redx') | null;
    shippedAt?: string | null;
    /**
     * Internal note for fulfillment staff (not shown to customers).
     */
    internalNote?: string | null;
  };
  statusTimeline?:
    | {
        status: 'processing' | 'shipped' | 'delivered' | 'completed' | 'cancelled' | 'refunded';
        updatedAt: string;
        id?: string | null;
      }[]
    | null;
  accessToken?: string | null;
  customerFullName?: string | null;
  customerPhone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: ('cash-on-delivery' | 'stripe') | null;
  cashOnDelivery?: {
    note?: string | null;
  };
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress: {
    district: string;
    fullAddress: string;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'BDT' | null;
  customerFullName?: string | null;
  customerPhone?: string | null;
  /**
   * Shared when one checkout creates multiple orders (different shipment profiles).
   */
  checkoutBatchId?: string | null;
  /**
   * Shipment group, delivery prefs, and charge lines for this order.
   */
  checkoutShipmentSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shipmentName?: string | null;
  shipmentCharge?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'BDT' | null;
  /**
   * Checkout coupon code (case-insensitive for customers).
   */
  appliedPromoCode?: string | null;
  promoCode?: (number | null) | PromoCode;
  promoDiscountAmount?: number | null;
  subtotalBeforeDiscount?: number | null;
  /**
   * Set when an abandoned-cart recovery email was sent.
   */
  abandonedCartEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Checkout promo codes: percentage or fixed discounts with optional product and category rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  /**
   * Case-insensitive for shoppers; stored in uppercase.
   */
  code: string;
  /**
   * Optional note for staff (not shown to customers).
   */
  internalLabel?: string | null;
  active?: boolean | null;
  /**
   * Leave empty for no start limit.
   */
  validFrom?: string | null;
  /**
   * Leave empty for no end limit.
   */
  validUntil?: string | null;
  discountType: 'percentage' | 'fixed';
  /**
   * 0–100. Applied to eligible subtotal.
   */
  discountPercentage?: number | null;
  /**
   * Fixed discount in whole taka (e.g. 50 for ৳50 off). Matches how you think in currency, not internal poisha.
   */
  discountFixedAmount?: number | null;
  /**
   * Optional maximum discount in whole taka (e.g. 500 for ৳500 cap on percentage promos).
   */
  maxDiscountAmount?: number | null;
  /**
   * Minimum cart subtotal in whole taka before the code applies (e.g. 1000 for ৳1,000 minimum).
   */
  minOrderSubtotal?: number | null;
  /**
   * If set, only these products count toward the discount. Leave empty for all products (except exclusions).
   */
  restrictToProducts?: (number | Product)[] | null;
  excludeProducts?: (number | Product)[] | null;
  /**
   * Products in any of these categories are excluded from the discount.
   */
  excludeCategories?: (number | Category)[] | null;
  /**
   * Max uses across all customers. Empty = unlimited.
   */
  maxRedemptionsTotal?: number | null;
  /**
   * Per signed-in customer (orders linked to their account). Empty = unlimited.
   */
  maxRedemptionsPerUser?: number | null;
  /**
   * Increments when an order is placed with this code.
   */
  timesRedeemed?: number | null;
  /**
   * Signed-in users only: no completed orders on their account.
   */
  firstTimeCustomersOnly?: boolean | null;
  /**
   * Optional. One domain per line (e.g. company.com). Applies to signed-in users with matching email.
   */
  allowedEmailDomains?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  district: string;
  fullAddress: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  customer: number | User;
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public comments appear on posts only after approval. Use the sidebar moderation status dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-comments".
 */
export interface BlogComment {
  id: number;
  post: number | Post;
  /**
   * Set automatically when a customer submits.
   */
  author?: (number | null) | User;
  /**
   * Up to 2,000 characters.
   */
  body: string;
  /**
   * Only approved comments appear on the live blog.
   */
  moderationStatus: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer ratings and written reviews. Shoppers only see approved reviews; authors see their own pending items.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews".
 */
export interface ProductReview {
  id: number;
  product: number | Product;
  /**
   * Set automatically when a customer submits a review.
   */
  author: number | User;
  /**
   * Captured at submit time for the public product page.
   */
  reviewerDisplayName: string;
  /**
   * Whole stars from 1 (poor) to 5 (excellent).
   */
  rating: number;
  /**
   * Optional short headline (e.g. “Great for kids”).
   */
  title?: string | null;
  /**
   * Share what you liked or what could be better.
   */
  body: string;
  /**
   * Automatically set when the reviewer completed an order that included this product.
   */
  verifiedPurchase?: boolean | null;
  /**
   * Only approved reviews appear to the public on the product page.
   */
  moderationStatus: 'pending' | 'approved' | 'rejected';
  /**
   * Internal note for staff (not shown on the storefront).
   */
  moderatorNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences".
 */
export interface NotificationPreference {
  id: number;
  user: number | User;
  pushEnabled?: boolean | null;
  priceDropAlerts?: boolean | null;
  stockAlerts?: boolean | null;
  orderUpdates?: boolean | null;
  marketingOptIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: number;
  user: number | User;
  platform: 'web' | 'mobile_web' | 'native';
  /**
   * Web Push subscription URL from the browser, or a placeholder like fcm:TOKEN for native apps (store token only until FCM is configured).
   */
  endpoint: string;
  p256dh?: string | null;
  auth?: string | null;
  /**
   * Optional. Helps debug subscription issues.
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-alerts".
 */
export interface ProductAlert {
  id: number;
  user: number | User;
  product: number | Product;
  /**
   * Optional. Leave empty for simple products without variants.
   */
  variant?: (number | null) | Variant;
  alertType: 'price_drop' | 'restock';
  /**
   * For price drops: notify when the price is at or below this amount (currency matches store). Leave empty to notify on any decrease.
   */
  targetPrice?: number | null;
  active?: boolean | null;
  fulfilledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notifications".
 */
export interface UserNotification {
  id: number;
  user: number | User;
  kind: 'price_drop' | 'restock' | 'broadcast' | 'system';
  title: string;
  body: string;
  /**
   * Path (e.g. /products/slug) or full URL opened when the notification is clicked.
   */
  linkUrl?: string | null;
  /**
   * Optional. Used for de-duplication and admin context.
   */
  product?: (number | null) | Product;
  /**
   * Set when this row was created from a broadcast campaign.
   */
  broadcast?: (number | null) | NotificationBroadcast;
  /**
   * For price-drop alerts: unit price before the change (default currency).
   */
  pricePrevious?: number | null;
  /**
   * For price-drop alerts: unit price after the change.
   */
  priceNow?: number | null;
  readAt?: string | null;
  /**
   * Delivery channels used for this message.
   */
  channels?: ('inbox' | 'push')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Schedule or send store-wide notifications. “Scheduled” rows are processed by the notifications cron job (see CRON_SECRET).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-broadcasts".
 */
export interface NotificationBroadcast {
  id: number;
  title: string;
  body: string;
  /**
   * Optional path or URL.
   */
  linkUrl?: string | null;
  /**
   * When status is “Scheduled”, sends at or after this time (UTC).
   */
  scheduledFor?: string | null;
  status: 'draft' | 'scheduled' | 'sending' | 'completed' | 'cancelled';
  segment: 'push_enabled' | 'marketing_opt_in';
  /**
   * Filled automatically after a run.
   */
  statsRecipients?: number | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Revenue, orders, carts, and store performance
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-dashboard".
 */
export interface SalesDashboard {
  id: number;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'blog-comments';
        value: number | BlogComment;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'product-reviews';
        value: number | ProductReview;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'shipments';
        value: number | Shipment;
      } | null)
    | ({
        relationTo: 'notification-preferences';
        value: number | NotificationPreference;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: number | PushSubscription;
      } | null)
    | ({
        relationTo: 'product-alerts';
        value: number | ProductAlert;
      } | null)
    | ({
        relationTo: 'user-notifications';
        value: number | UserNotification;
      } | null)
    | ({
        relationTo: 'notification-broadcasts';
        value: number | NotificationBroadcast;
      } | null)
    | ({
        relationTo: 'sales-dashboard';
        value: number | SalesDashboard;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        brandsCarousel?: T | BrandsCarouselBlockSelect<T>;
        featuredCategories?: T | FeaturedCategoriesBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        topSellingProducts?: T | TopSellingProductsBlockSelect<T>;
        productShowcase?: T | ProductShowcaseBlockSelect<T>;
        exclusiveComboDeals?: T | ExclusiveComboDealsBlockSelect<T>;
        twoImagePromo?: T | TwoImagePromoBlockSelect<T>;
        singleImageBanner?: T | SingleImageBannerBlockSelect<T>;
        promoCarouselSplit?: T | PromoCarouselSplitBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandsCarouselBlock_select".
 */
export interface BrandsCarouselBlockSelect<T extends boolean = true> {
  heading?: T;
  brands?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCategoriesBlock_select".
 */
export interface FeaturedCategoriesBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TopSellingProductsBlock_select".
 */
export interface TopSellingProductsBlockSelect<T extends boolean = true> {
  heading?: T;
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseBlock_select".
 */
export interface ProductShowcaseBlockSelect<T extends boolean = true> {
  heading?: T;
  viewAllUrl?: T;
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExclusiveComboDealsBlock_select".
 */
export interface ExclusiveComboDealsBlockSelect<T extends boolean = true> {
  heading?: T;
  viewAllUrl?: T;
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoImagePromoBlock_select".
 */
export interface TwoImagePromoBlockSelect<T extends boolean = true> {
  leftImage?: T;
  rightImage?: T;
  leftLink?: T;
  rightLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SingleImageBannerBlock_select".
 */
export interface SingleImageBannerBlockSelect<T extends boolean = true> {
  image?: T;
  link?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoCarouselSplitBlock_select".
 */
export interface PromoCarouselSplitBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  rightImage?: T;
  rightLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        quote?: T;
        photo?: T;
        name?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  author?: T;
  relatedPosts?: T;
  excerpt?: T;
  featuredYoutubeUrl?: T;
  featuredImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-comments_select".
 */
export interface BlogCommentsSelect<T extends boolean = true> {
  post?: T;
  author?: T;
  body?: T;
  moderationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  generateSlug?: T;
  slug?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  customer?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  address?: T;
  roles?: T;
  staffPermissions?: T;
  staffGrants?:
    | T
    | {
        page?: T;
        actions?: T;
        id?: T;
      };
  orders?: T;
  cart?: T;
  addresses?: T;
  wishlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  district?: T;
  fullAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInBDTEnabled?: T;
  priceInBDT?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInBDTEnabled?: T;
  priceInBDT?: T;
  discountPercentage?: T;
  productBadge?: T;
  technicalSpecs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  relatedProducts?: T;
  reviewAverageRating?: T;
  reviewCount?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  subcategories?: T;
  brand?: T;
  shipment?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  internalLabel?: T;
  active?: T;
  validFrom?: T;
  validUntil?: T;
  discountType?: T;
  discountPercentage?: T;
  discountFixedAmount?: T;
  maxDiscountAmount?: T;
  minOrderSubtotal?: T;
  restrictToProducts?: T;
  excludeProducts?: T;
  excludeCategories?: T;
  maxRedemptionsTotal?: T;
  maxRedemptionsPerUser?: T;
  timesRedeemed?: T;
  firstTimeCustomersOnly?: T;
  allowedEmailDomains?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews_select".
 */
export interface ProductReviewsSelect<T extends boolean = true> {
  product?: T;
  author?: T;
  reviewerDisplayName?: T;
  rating?: T;
  title?: T;
  body?: T;
  verifiedPurchase?: T;
  moderationStatus?: T;
  moderatorNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  appliedPromoCode?: T;
  promoCode?: T;
  promoDiscountAmount?: T;
  subtotalBeforeDiscount?: T;
  abandonedCartEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        district?: T;
        fullAddress?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  checkoutCart?: T;
  appliedPromoCode?: T;
  promoCode?: T;
  promoDiscountAmount?: T;
  subtotalBeforeDiscount?: T;
  checkoutBatchId?: T;
  checkoutShipmentSummary?: T;
  shipmentName?: T;
  shipmentCharge?: T;
  fulfillment?:
    | T
    | {
        trackingNumber?: T;
        carrier?: T;
        shippedAt?: T;
        internalNote?: T;
      };
  statusTimeline?:
    | T
    | {
        status?: T;
        updatedAt?: T;
        id?: T;
      };
  accessToken?: T;
  customerFullName?: T;
  customerPhone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  cashOnDelivery?:
    | T
    | {
        note?: T;
      };
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        district?: T;
        fullAddress?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  customerFullName?: T;
  customerPhone?: T;
  checkoutBatchId?: T;
  checkoutShipmentSummary?: T;
  shipmentName?: T;
  shipmentCharge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments_select".
 */
export interface ShipmentsSelect<T extends boolean = true> {
  shippingName?: T;
  dhakaPointDeliveryCharge?: T;
  dhakaHomeDeliveryCharge?: T;
  outsideDhakaPointDeliveryCharge?: T;
  outsideDhakaHomeDeliveryCharge?: T;
  freeDelivery?: T;
  cumulativeCount?: T;
  cumulativeCharge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences_select".
 */
export interface NotificationPreferencesSelect<T extends boolean = true> {
  user?: T;
  pushEnabled?: T;
  priceDropAlerts?: T;
  stockAlerts?: T;
  orderUpdates?: T;
  marketingOptIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  platform?: T;
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-alerts_select".
 */
export interface ProductAlertsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  variant?: T;
  alertType?: T;
  targetPrice?: T;
  active?: T;
  fulfilledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notifications_select".
 */
export interface UserNotificationsSelect<T extends boolean = true> {
  user?: T;
  kind?: T;
  title?: T;
  body?: T;
  linkUrl?: T;
  product?: T;
  broadcast?: T;
  pricePrevious?: T;
  priceNow?: T;
  readAt?: T;
  channels?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-broadcasts_select".
 */
export interface NotificationBroadcastsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  linkUrl?: T;
  scheduledFor?: T;
  status?: T;
  segment?: T;
  statsRecipients?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-dashboard_select".
 */
export interface SalesDashboardSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}